### ISSUE TITLE
Question about "-- classifier_loss_scaling"

### ISSUE THREAD

**Issue by ggaooya** [KamilDeja/joint_diffusion#1]
Hello, I would like to know what’s the value of "-- classifier_loss_scaling" to obtain the classification accuracy of the four datasets in the paper?

**Comment by KamilDeja** [comment]
Hi ggaooya, thank you for your question. I'll update the readme with the exact training parameters, but for the main experiments the scaling parameter was _--classifier_loss_scaling 0.001_ for all datasets.

**Comment by KamilDeja** [comment]
I updated the readme, feel free to contact me with any additional questions

**Comment by ggaooya** [comment]
OK! Thank you very much!
