### ISSUE TITLE
Configurations for semi-supervised learning

### ISSUE THREAD

**Issue by won-bae** [KamilDeja/joint_diffusion#2]
Hi authors, 

Thank you for sharing the code for a great work. I was wondering if the current implementation has a functionality to reproduce the result for semi-supervised learning settings. According to my understanding, `classifier_train.py` does not have that implemented. If it is implemented somewhere, could you direct me to the script and corresponding configurations you used?
Thank you in advance.

**Comment by KamilDeja** [comment]
Hi,
Thank you for your comment! :)
`classifier_train.py `script is an original script from openai guided diffusion repo, that we used only for comparison - it is used solely for the training of the standard external calssifier used for classical guidance. Training  of our methods is done with `image_train.py` script. As explained in the readme if you specify  `--train_with_classifier True` you will train the diffusion together with a joint classifier. If you want to train it in semi-supervised setting, there is additional flag that controls the share of the training data labels. e.g. with `--labelled_data_share 0.01` you'll train the model with 1% of labels.

If you want to take a look into details, training of the classifier with limited number of labels is implemented in the calculate_classifier_loss function in gaussian_diffusion.py script:
[calculate_classifier_loss](https://github.com/KamilDeja/joint_diffusion/blob/e5dc30b073df8bc0e4abea3863fd067db68d5f37/guided_diffusion/gaussian_diffusion.py#L800)

Don't hesitate to contact me if you have any further questions!

**Comment by won-bae** [comment]
Hi,

Sorry for the late reply. I wanted to verify whether it works and come up with further questions but it works great with your instruction and I do not have any further questions at the moment. Thank you for your reply again!
