### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by Ahmad-Omar-Ahsan** [KamilDeja/joint_diffusion#3]
Hello, 

Thank you for the code for the joint diffusion paper. I was wondering about how to prepare a custom dataset for training the joint diffusion model. Should I follow the openAI's preparation steps? Secondly, what should I do in the `dataloader/base.py` to incorporate my custom dataset?

**Comment by KamilDeja** [comment]
Hi, Yes, you can follow the openAI's preparation steps to prepare the folder with images (unless you already have this structure). Then I'd suggest to use base.py script as you alreday noticed. For example, you can take a look into [Malaria dataset](https://github.com/KamilDeja/joint_diffusion/blob/e5dc30b073df8bc0e4abea3863fd067db68d5f37/dataloaders/base.py#L604) , it just uses images stored in the folder specified in the script that are loaded to the torchvision ImageDataset. The function should return train_dataset, test_dataset, resolution and number_of_channels. If you have access to servers with good memory, I'd suggest using the FastDataset interface (You can see the usage in the Birds or CelebA dataset). It just loads all of the images from the disc to the RAM memory what significantly speeds up the training.

**Comment by Ahmad-Omar-Ahsan** [comment]
Thank you for the reply.
